#!/bin/sh

set -e

# Pass maintainer script parameters to hook scripts
export DEB_MAINT_PARAMS=""

# Tell initramfs builder whether it's wanted
export INITRD=Yes

test -d /etc/kernel/postrm.d && run-parts --arg="4.2.0-rc1-46" --arg="/boot/vmlinuz-4.2.0-rc1-46" /etc/kernel/postrm.d
exit 0
