#!/bin/sh

set -e

# Pass maintainer script parameters to hook scripts
export DEB_MAINT_PARAMS=""

# Tell initramfs builder whether it's wanted
export INITRD=Yes

test -d /etc/kernel/postinst.d && run-parts --arg="4.6.3-133" --arg="/boot/vmlinuz-4.6.3-133" /etc/kernel/postinst.d
exit 0
